# Generated by Django 5.0.2 on 2024-04-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
